nube/nube/urls.py
from django.contrib import admin
from django.urls import path
from .views import*
import re
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include

from ninja import NinjaAPI
from prueba.api import router as api_router

api= NinjaAPI()
api.add_router("/api/",api_router)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entrada',entrada, name="entrada"),
    path('hijo/',hijo, name="hijo"),
    url(r'^', include('prueba.urls')),
    url(r'^', include('pasteleria.urls')),
    url(r'^', include('pizzeria.urls')),
    #path("api/",api.urls),
]




#if settings.MEDIA_URL.startswith("/"):
#   urlpatterns += [
 #       url(
  #          r'^{MEDIA_URL}(?P<path>.*)$'.format(MEDIA_URL=re.escape(settings.MEDIA_URL.lstrip('/'))),
   #         serve,
    #        {'document_root': settings.MEDIA_ROOT},
     #   ),
    #]
if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nube/prueba/urls.py
from django.contrib import admin
from django.urls import path
from .views import*
import re
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from .views import *



urlpatterns = [
    path('prueba/listar/',listar,name="listar"),
    path('prueba/crear/', carrocrear, name='crear'),
    path('prueba/eliminar/<int:id>',eliminar,name='eliminar'),
    path('prueba/actualizar/<int:id>',actualizar,name='actualizar'),
]

nube/prueba/models.py
from django.db import models
from  django.conf import settings


# Create your models here.
class carro(models.Model):
    color=models.CharField(max_length=20, blank=True, null=True)
    modelo= models.CharField(max_length=20, blank=True, null=True)
    anio= models.IntegerField()
    marca=models.CharField(max_length=20, blank=True, null=True)

nube/prueba/forms.py
from multiprocessing.sharedctypes import Value
from urllib import request
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class agregar(forms.ModelForm):
	class Meta:
		model=carro
		fields= ['id','color','modelo','anio','marca']

nube/prueba/views.py
from django.shortcuts import render
from .models import carro
from .forms import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django import forms 
from django.views.generic import ListView, DetailView 
from django.contrib.messages.views import SuccessMessageMixin 
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.
def listar(request):
    carros= carro.objects.all()
    template="prueba/listar.html"
    context={
        'carros': carros,

    }
    return render (request,template,context)

def carrocrear(request): 
    if request.method=='POST':
        form= agregar(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar')

    form = agregar 
    context={
        'form':form,

    }
    return render (request, "prueba/agregar.html", context)
def eliminar(request, id):
  member = carro.objects.get(id=id)
  member.delete()
  return redirect(reverse('listar'))

def actualizar(request, id):
    if request.method=='POST':
        instance=carro.objects.get(id=id)
        form=agregar(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('listar')
    
    dato = carro.objects.get(id=id)
    #form= agregar()
    #form=mymember
    template = 'prueba/actualizar.html'
    context = {
    'dato': dato,
    #'form':form,
    }
    return render(request, template, context)

  
  
  

  
  
  

nube/templates/prueba/actualizar.html
{% extends "base.html" %}
{% block content %}
{{ dato.color}}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><label for="id_color">Color:</label> <input type="text" name="color" maxlength="20" id="id_color" value="{{dato.color}}"></p>
    <p><label for="id_modelo">Modelo:</label> <input type="text" name="modelo" maxlength="20" id="id_modelo" value="{{dato.modelo}}"></p>
    <p><label for="id_anio">Anio:</label> <input type="number" name="anio" required="" id="id_anio" value="{{dato.anio}}"></p>
    <p><label for="id_marca">Marca:</label> <input type="text" name="marca" maxlength="20" id="id_marca" value="{{dato.marca}}"></p>
       

        <button type="submit" class="btn btn-primary">Actualizar</button>

</form>
{% endblock content %}

nube/templates/prueba/agregar.html
{% extends "base.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
         {{ form.as_p }}
       

        <button type="submit" class="btn btn-primary">Aceptar</button>

    </form>
{% endblock content %}

nube/templates/prueba/listar.html
{% extends "base.html" %}
{% block content %}

<button onclick="location.href='/prueba/crear'">agregar</button>

    <table>

        <tr>

        <th>color</th>
        <th>modelo</th>
        <th>año</th>
        <th>marca</th>
        <th>accion1</th>
        <th>accion2</th>

        </tr>
        {% for n in carros %}        
            <tr>
            <td>{{n.color}}</td>
            <td>{{n.modelo}}</td>
            <td>{{n.anio}}</td>
            <td>{{n.marca}}</td>
            <td><button id="{{n.id}}" onclick="location.href='/prueba/actualizar/{{n.id}}'">actualizar</button></td>
            <td><button id="{{n.id}}" onclick="location.href='/prueba/eliminar/{{n.id}}'">eliminar</button></td>
            </tr>
        
        </table>
    {% endfor %}

{% endblock content %}